### ISSUE TITLE
Rollback results in broken symlink

### ISSUE THREAD

**Issue by leigh-ols** [deployphp/deployer#1182]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 14.04

### Description 
When rolling back the symlink created points to `10` rather than `releases/10`,

The command being executed is:
```bash
cd /home/site && (cd /home/site && ln -nfs --relative /home/site/releases/10 current)
```

Which for reasons I don't understand creates a symlink `/home/site/current -> 10`

Manually executing the same command results in the same broken symlink.

Removing the unnecessary double `cd /home/site &&` resolves the issue.

https://github.com/deployphp/deployer/blob/542e5f0dc279dbd2a21169c87c5f093a9cd2960e/recipe/deploy/rollback.php#L18

### Steps to reproduce
Deploy and then rollback.

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require 'recipe/common.php';
require __DIR__.'/vendor/deployer/recipes/rsync.php';

set('writable_use_sudo', false); // Using sudo in writable commands
set('shared_dirs', ['wordpress/wp-content/uploads']);
#set('shared_files', ['config/wp-config.php']);

set('env_vars', 'DB_NAME=dbname');
set('rsync_src', __DIR__);
set('rsync',[
    'exclude'      => [
        '.git',
        'deploy.php',
    ],
    'exclude-file' => false,
    'include'      => [],
    'include-file' => false,
    'filter'       => [],
    'filter-file'  => false,
    'filter-perdir'=> false,
    'flags'        => 'rzl', // Recursive, with compress
    'options'      => ['delete'],
    'timeout'      => 60,
]);

// Servers
server('production', 'mysite.com')
    ->user('username')
    ->password()
    ->set('deploy_path', '/home/site')
    ->stage('production');

// Tasks
desc('Install wordpress');
task('install-wordpress', function() {
    // Set up environment
    if (!askConfirmation('Use default database credentials')) {
        $db_host = ask('Override default database host?', 'localhost');
        $db_name = ask('Override default database name?', 'dbname');
        $db_user = ask('Override default database user?', 'dbuser');
        $db_pass = askHiddenResponse('dbpwd?');
        $release_path = get('release_path');

        $args = "--db-host $db_host --db-name $db_name --db-user $db_user --db-pass $db_pass";
        run('cd {{release_path}}/wordpress && ./generate-env '.$args);
    }

    // Install wordpress+plugins etc
    run('cd {{release_path}}/wordpress && ./install.sh');
});
before('deploy:symlink', 'install-wordpress');


desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'rsync',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
]);

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

### Output log
*With enabled option for verbose output `-vvv`.*
```
➤ Executing task rollback
[production] > cd /home/site && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "
false")
[user@mysite.com] Password:
[production] < true
[production] > cd /home/site && (cd releases && ls -t -1 -d */)
[production] < 10/
[production] < 9/
[production] < 8/
[production] > cd /home/site && (if [ -f .dep/releases ]; then echo "true"; fi)
[production] < true
[production] > cd /home/site && (tail -n 15 .dep/releases)
[production] < 20170420153846,1
[production] < 20170420153955,2
[production] < 20170420154134,3
[production] < 20170420154425,4
[production] < 20170420155136,5
[production] < 20170420155540,6
[production] < 20170420155634,7
[production] < 20170420160109,8
[production] < 20170420161024,9
[production] < 20170420164654,10
[production] < 20170420164903,10
[production] < 20170420165014,11
[production] < 20170420165151,11
[production] < 20170420165227,11
[production] < 20170420165432,12
[production] > cd /home/site && (if [[ "$(man ln)" =~ "--relative" ]]; then echo "true"; fi)
[production] < true
[production] > cd /home/site && (ln -nfs --relative /home/site/releases/9 current)
[production] > cd /home/site && (rm -rf /home/site/releases/10)
```

**Comment by leigh-ols** [comment]
I think 'minor bug' is a bit light for this one, this is a bug that entirely breaks a part of deployers core functionality and causes production sites to completely fall off the internet.

**Comment by antonmedv** [comment]
Please, try new version of deployer from master branch.

**Comment by leigh-ols** [comment]
```
require-dev: {
    deployer/deployer: dev-master
    deployer/recipes: ^4.0
}
```

```bash
rm vendor/ -rf
rm composer.lock
composer install
./vendor/bin/dep init
```

results in:

```
 [Error] Call to undefined function Deployer\server()                                                             
                                                                                                                  

 #0 /home/leigh/tmp/storiel/wordpress/vendor/deployer/deployer/src/Deployer.php(309): require()                   
 #1 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                  
 #2 /home/leigh/tmp/storiel/wordpress/vendor/deployer/deployer/src/Deployer.php(310):                             
 call_user_func(Object(Closure))                                                                                  
 #3 /home/leigh/tmp/storiel/wordpress/vendor/deployer/deployer/bin/dep(111): Deployer\Deployer::run('dev-master', 
 '/home/leigh/tmp...')                                                                                            
 #4 {main}                                                       
```


Am I doing something obviously wrong here?

**Comment by antonmedv** [comment]
Yes, please take a look at: 
https://github.com/deployphp/docs/blob/master/hosts.md
https://github.com/deployphp/deployer/blob/master/UPGRADE.md

Now i trying to reproduce bug on 16.04. Look like but in coreutils bug. Please run this: `apt-cache policy coreutils` What version?

**Comment by antonmedv** [comment]
There is a bug in `ln -r` command in `8.21` coreutils.

**Comment by antonmedv** [comment]
ubuntu 14.04 goes with 8.21.

**Comment by antonmedv** [comment]
To solve in v5 add:
```php
set('use_relative_symlink', false);
```

**Comment by antonmedv** [comment]
https://github.com/deployphp/deployer/blob/master/KNOWN_BUGS.md#ubuntu-1404-coreutils-821
