### ISSUE TITLE
CI's job succeeded even there is an PHP error inside

### ISSUE THREAD

**Issue by dakur** [deployphp/deployer#1236]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0.1
| Local Machine OS  | Ubuntu 14.04.5 LTS
| Remote Machine OS | -

### Description 
When I've accidentally made typo in function name, CI job has succeeded even there was an error inside the job. I guess there is some bad exit code.

### Steps to reproduce
Set up a deploy with bad function name (I typed `host()` instead of `hostname()`) and make a deploy in GitLab CI.

### Content of `deploy.php`
```php
<?php

namespace Deployer;


/** @noinspection PhpIncludeInspection recipe comes from Deployer tool */
require 'recipe/common.php';



// CONFIGURATION

set('ssh_type', 'native');
set('ssh_multiplexing', TRUE);

set('shared_files', [
	'...',
]);
set('shared_dirs', [
	'...',
]);
set('writable_dirs', [
	'...',
]);


// SERVERS

host('mysite')
	->stage('mysite')
	->host('10.0.0.2') // typo in here
	->port(22)
	->user('someuser')
	->identityFile('/root/.ssh/id_rsa')
	->set('deploy_path', '/var/www/web');

// TASKS

task('deploy:copy_application', function () {
	upload('..', '{{release_path}}');
});

// For definitions of tasks bellow:
// @see https://github.com/deployphp/deployer/tree/master/recipe/deploy
desc('Deploy your project');
task('deploy', [
	'deploy:prepare',
	'deploy:lock',
	'deploy:release',

	'deploy:copy_application',

	'deploy:copy_dirs',

	'deploy:shared',
	'deploy:writable',

	'deploy:symlink',

	'deploy:unlock',
	'cleanup',
	'success',
]);

after('deploy:failed', 'deploy:unlock');

```

### Output log
```
 dep deploy mysite --ansi -vvv

 [Error] Call to undefined method Deployer\Host\Host::host()                    

 #0 /root/.composer/vendor/deployer/deployer/src/Deployer.php(309): require()   
 #1 [internal function]: Deployer\Deployer::Deployer\{closure}()                
 #2 /root/.composer/vendor/deployer/deployer/src/Deployer.php(310):             
 call_user_func(Object(Closure))                                                
 #3 /root/.composer/vendor/deployer/deployer/bin/dep(120):                      
 Deployer\Deployer::run('master', '/builds/nakloub...')                         
 #4 {main}                                                                      

Job succeeded
```

**Comment by antonmedv** [comment]
Fixed.
