### ISSUE TITLE
Error in command run

### ISSUE THREAD

**Issue by marciosatin** [deployphp/deployer#1524]
### error trace
```php
Run: cd /home/apprichi/deploy && cat ./releases/release-deployed.txt
PHP Warning:  unpack(): Type N: not enough input, need 4, have 1 in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php on line 2749

Warning: unpack(): Type N: not enough input, need 4, have 1 in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php on line 2749
PHP Warning:  extract() expects parameter 1 to be array, boolean given in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php on line 2749

Warning: extract() expects parameter 1 to be array, boolean given in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php on line 2749
PHP Fatal error:  Uncaught Error: Call to undefined function phpseclib\Net\utf8_decode() in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php:2750
Stack trace:
#0 phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php(2694): phpseclib\Net\SSH2->_filter('\x00\x00\x17hostkeys-00@...')
#1 phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php(2897): phpseclib\Net\SSH2->_get_binary_packet()
#2 phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SFTP.php(402): phpseclib\Net\SSH2->_get_channel_packet(256)
#4 phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php(99): Deployer\Server\Remote\PhpSecLib->connect()
#5 phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php(108): Deployer\Server\Remote\PhpSecLib->checkConnection()
#6 phar:///usr/local/bin/dep/src/functions.php(289): Deployer\Server\Remote\PhpSecLib->run('cd /home/appric.. in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php on line 2750

Fatal error: Uncaught Error: Call to undefined function phpseclib\Net\utf8_decode() in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php:2750
Stack trace:
#0 phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php(2694): phpseclib\Net\SSH2->_filter('\x00\x00\x17hostkeys-00@...')
#1 phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php(2897): phpseclib\Net\SSH2->_get_binary_packet()
#2 phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SFTP.php(402): phpseclib\Net\SSH2->_get_channel_packet(256)
#4 phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php(99): Deployer\Server\Remote\PhpSecLib->connect()
#5 phar:///usr/local/bin/dep/src/Server/Remote/PhpSecLib.php(108): Deployer\Server\Remote\PhpSecLib->checkConnection()
#6 phar:///usr/local/bin/dep/src/functions.php(289): Deployer\Server\Remote\PhpSecLib->run('cd /home/appric.. in phar:///usr/local/bin/dep/vendor/deployer/phpseclib/phpseclib/Net/SSH2.php on line 2750
```

**Comment by antonmedv** [comment]
https://github.com/deployphp/deployer/blob/master/.github/CONTRIBUTING.md
