### ISSUE TITLE
 [Error] Call to a member function getOutput() on string                                                                

### ISSUE THREAD

**Issue by JeancarloPerez** [deployphp/deployer#1595]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | OSX
| Remote Machine OS | Ubuntu

### Description 
Hello, I'm new using Deployer, so I create a deployment but when I run `dep deploy example` I retrieve an error, please help me.

### Content of `deploy.php`
```php
namespace Deployer;

require 'recipe/common.php';

set('application', 'Deployments');
set('repository', 'https://bitbucket.org/xxxx/xxxxx.git');
set('git_tty', true);
set('shared_files', ['public/wp-config.php']);
set('shared_dirs', ['public/wp-content/uploads']);
add('writable_dirs', []);
set('keep_releases', 3);
set('composer_command', 'composer');
set('branch', 'master');

// Hosts
host('example')
    ->hostname('example')
    ->port(22)
    ->user('user')
    ->configFile('~/.ssh/config')
    ->identityFile('~/.ssh/id_rsa_xxxx')
    ->set('deploy_path', '/var/www/html/deploy');

task('deploy:write_version', function () {
  cd(get('deploy_path') . '/current/public/');
  run('git rev-parse HEAD > version.txt');
});

task('info:version', function() {
  cd(get('deploy_path') . '/current');
  $version = run('git rev-parse HEAD')->getOutput();
  write("Currently deployed commit: <info>$version</info>");
});



/**
 * Main task
 */
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:vendors',
	  'deploy:symlink',
    'deploy:write_version',
    'cleanup',
    'info:version',
])->desc('Deploy your project');
after('deploy', 'success');
```

### Output log
```
[Error] Call to a member function getOutput() on string                                                                
                                                                                                                        

 #0 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #1 /Applications/MAMP/htdocs/deployment/deployment/vendor/deployer/deployer/src/Task/Task.php(105):                    
 call_user_func(Object(Closure))                                                                                        
 #2 /Applications/MAMP/htdocs/deployment/deployment/vendor/deployer/deployer/src/Executor/SeriesExecutor.php(63):       
 Deployer\Task\Task->run(Object(Deployer\Task\Context))                                                                 
 #3 /Applications/MAMP/htdocs/deployment/deployment/vendor/deployer/deployer/src/Console/TaskCommand.php(142):          
 Deployer\Executor\SeriesExecutor->run(Array, Array)                                                                    
 #4 /Applications/MAMP/htdocs/deployment/deployment/vendor/symfony/console/Command/Command.php(252):                    
 Deployer\Console\TaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),                               
 Object(Deployer\Console\Output\OutputWatcher))                                                                         
 #5 /Applications/MAMP/htdocs/deployment/deployment/vendor/symfony/console/Application.php(865):                        
 Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),                      
 Object(Deployer\Console\Output\OutputWatcher))                                                                         
 #6 /Applications/MAMP/htdocs/deployment/deployment/vendor/deployer/deployer/src/Console/Application.php(133):          
 Symfony\Component\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand),                              
 Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))                      
 #7 /Applications/MAMP/htdocs/deployment/deployment/vendor/symfony/console/Application.php(241):                        
 Deployer\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand),                                       
 Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))                      
 #8 /Applications/MAMP/htdocs/deployment/deployment/vendor/symfony/console/Application.php(143):                        
 Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),                        
 Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                
 #9 /Applications/MAMP/htdocs/deployment/deployment/vendor/deployer/deployer/src/Deployer.php(331):                     
 Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),                          
 Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                
 #10 phar:///usr/local/bin/dep/bin/dep(119): Deployer\Deployer::run('v6.1.0', '/Applications/M...')                     
 #11 /usr/local/bin/dep(4): require('phar:///usr/loc...')                                                               
 #12 {main}                                     
```

**Comment by JeancarloPerez** [comment]
Thanks, It works
