### ISSUE TITLE
How to process environment variables for host configuration correctly?

### ISSUE THREAD

**Issue by pschirch** [deployphp/deployer#1807]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.4.3
| Local Machine OS  | Ubuntu 18.04
| Remote Machine OS | N/A

### Description 

We want to use Deployer in our container-infrastructure. The settings are pushed by environment variables. If I use get() inside of a task all works fine. But we also push the host configuration, which can not be processed due a closure context issue. I prepared a scaled-down version to demonstrate what I mean.

How to process environment variables for host configuration correctly?

### Steps to reproduce

```bash
export DEPLOYER__SERVER_HOSTNAME=myhost.com && dep test -vvv
```
### Content of `deploy.php`
```php
<?php

namespace Deployer;

require_once 'recipe/common.php';

set('env', function () {
    $environmentVariables = array_filter(
        $_SERVER,
        function ($key) {
            return strpos($key, 'DEPLOYER__') === 0;
        },
        ARRAY_FILTER_USE_KEY
    );

    return $environmentVariables;
});

set('server_hostname', function () {
    $environmentVariables = get('env');
    return (string) $environmentVariables['DEPLOYER__SERVER_HOSTNAME'];
});

host(get('server_hostname'));

task('test', function() {
    writeln(get('server_hostname'));
});
```

### Output log
```
PHP Warning:  preg_match() expects parameter 2 to be string, object given in /home/content-sync/.composer/vendor/deployer/deployer/src/Host/Range.php on line 18

                                                                                                                        
 [TypeError] Argument 1 passed to Deployer\Collection\Collection::has() must be of the type string, object given, called
             in /home/content-sync/.composer/vendor/deployer/deployer/src/functions.php on line 45                      
                                                                                                                        

 #0 /home/content-sync/.composer/vendor/deployer/deployer/src/functions.php(45):                                        
 Deployer\Collection\Collection->has(Object(Closure))                                                                   
 #1 /content-sync/deploy.php(24): Deployer\host(Object(Closure))                                                        
 #2 /home/content-sync/.composer/vendor/deployer/deployer/src/Deployer.php(325): require('/content-sync/d...')          
 #3 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #4 /home/content-sync/.composer/vendor/deployer/deployer/src/Deployer.php(326): call_user_func(Object(Closure))        
 #5 /home/content-sync/.composer/vendor/deployer/deployer/bin/dep(126): Deployer\Deployer::run('master',                
 '/content-sync/d...')                                                                                                  
 #6 {main} 
```

**Comment by antonmedv** [comment]
You can't use it on init stage `host(get('server_hostname'));`

**Comment by antonmedv** [comment]
What is output of get('server_hostname')?

**Comment by pschirch** [comment]
@antonmedv 
```bash
string(10) "myhost.com"
```

**Comment by pschirch** [comment]
@antonmedv How i can use the init stage to dynamically add hosts with values mapped from environment variables?

**Comment by antonmedv** [comment]
Like this:
```php
<?php

namespace Deployer;

require_once 'recipe/common.php';

$environmentVariables = array_filter(
        $_SERVER,
        function ($key) {
            return strpos($key, 'DEPLOYER__') === 0;
        },
        ARRAY_FILTER_USE_KEY
);


host($environmentVariables['DEPLOYER__SERVER_HOSTNAME']);
```

**Comment by pschirch** [comment]
Im aware of the closure context issue and that I can access `$environmentVariables` directly. But on the init stage I want to control the environment variable mapping and implement some logic to determine missing parameters etc.

**Comment by antonmedv** [comment]
Just plain php for that

**Comment by dmitrijscho** [comment]
you should pass string in host() instead of `get()`, in deploy.php line `host(get('server_hostname'));`
