### ISSUE TITLE
[InvalidArgumentException] Host `` not found

### ISSUE THREAD

**Issue by kanevbg** [deployphp/deployer#1980]
```
#0 /home/ws3/.config/composer/vendor/deployer/deployer/src/Collection/Collection.php(35):                              
 Deployer\Host\HostCollection->throwNotFound('192.168.255.55')                                                          
 #1 [internal function]: Deployer\Collection\Collection->get('192.168.255.55')                                          
 #2 /home/ws3/.config/composer/vendor/deployer/deployer/src/functions.php(49): array_map(Array, Array)                  
 #3 /home/ws3/project-name/deploy.php(64): Deployer\host('192.168.255.54', '192.168.255.55', '192.168.255.56')           
 #4 /home/ws3/.config/composer/vendor/deployer/deployer/src/Deployer.php(325): require('/home/ws3/proje...')            
 #5 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #6 /home/ws3/.config/composer/vendor/deployer/deployer/src/Deployer.php(326): call_user_func(Object(Closure))          
 #7 /home/ws3/.config/composer/vendor/deployer/deployer/bin/dep(126): Deployer\Deployer::run('master',                  
 '/home/ws3/proje...')                                                                                                  
 #8 {main}
```

The deploy.php file defines 3 more single-hosts (one of which is `host('192.168.255.54')`) before defining the host with three IPs as follows:
`host('192.168.255.54', '192.168.255.55', '192.168.255.56')`

EDIT: Same happens if using `host('192.168.255.[54:56]')`

Tested with:
PHP 7.2.19 + Deployer 6.4.3
PHP 7.2.24 + Deployer 6.6.0

EDIT2: It seems the reason is that `192.168.255.54` is defined as single-host, than defined again with `host('192.168.255.[54:56]')` in both `host` definitions the `stage` is different

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
