### ISSUE TITLE
ParseError on a fresh installation

### ISSUE THREAD

**Issue by SturmB** [deployphp/deployer#1984]
I've got a fresh installation of Linux, PHP, and Composer. I installed the latter globally, btw. And now, after a fresh installation of Deployer, the first time I run it I am greeted with a syntax error: 

```
 [ParseError] syntax error, unexpected ')'


 #0 [internal function]: Deployer\Deployer::Deployer\{closure}()
 #1 phar:///usr/local/bin/dep/src/Deployer.php(396): call_user_func(Object(Closure))
 #2 phar:///usr/local/bin/dep/src/Deployer.php(322): Deployer\Deployer::loadRecipe('/mnt/c/Users/ch...')
 #3 phar:///usr/local/bin/dep/bin/dep(134): Deployer\Deployer::run('6.7.3', '/mnt/c/Users/ch...')
 #4 /usr/local/bin/dep(4): require('phar:///usr/loc...')
 #5 {main}
```

Can anyone please explain to me what I have done wrong and how to fix this?

**Comment by SturmB** [comment]
Never mind. My mistake. I genuinely had a syntax error in my `deploy.php` file.

I guess I cannot delete this, but at least I can close it.
