### ISSUE TITLE
How to rollback Phinx migrations

### ISSUE THREAD

**Issue by GlennM** [deployphp/deployer#1987]
Hi,

I'm using the [Phinx](https://deployer.org/recipes/phinx.html) recipe in my deployment, which seems to work (my database gets populated during deployment).

Now I'm trying to include a rollback scenario where:
* I rollback the migrations (that haven been migrated in this deployment/release)
* I rollback the code
* I unlock the deployment

However, `phinx:rollback` doesn't work nicely.

The error on GitLab CI:
```
Executing task phinx:rollback
  [ArgumentCountError] Too few arguments to function                             
                       Deployer\Deployer::Deployer\{closure}(), 0 passed and     
                       exactly 1 expected                                        
  #0 [internal function]: Deployer\Deployer::Deployer\{closure}()                
  #1                                                                             
  /builds/***/vendor/deployer/deployer/src/Configuration/Confi
  guration.php(59): call_user_func(Object(Closure))                              
  #2                                                                             
  /builds/***/vendor/deployer/deployer/src/functions.php(549):
  Deployer\Configuration\Configuration->get('phinx_get_allow...', NULL)          
  #3                                                                             
  /builds/***/vendor/deployer/recipes/recipe/phinx.php(130):  
  Deployer\get('phinx_get_allow...')                                             
  #4 [internal function]: Deployer\Deployer::Deployer\{closure}()                
  #5                                                                             
  /builds/***/vendor/deployer/deployer/src/Task/Task.php(105):
  call_user_func(Object(Closure))                                                
  #6                                                                             
  /builds/***/vendor/deployer/deployer/src/Executor/SeriesExec
  utor.php(60): Deployer\Task\Task->run(Object(Deployer\Task\Context))           
  #7                                                                             
  /builds/***/vendor/deployer/deployer/src/Console/TaskCommand
  .php(157): Deployer\Executor\SeriesExecutor->run(Array, Array)                 
  #8                                                                             
  /builds/***/vendor/symfony/console/Command/Command.php(255):
  Deployer\Console\TaskCommand->execute(Object(Symfony\Component\Console\Input\Ar
  gvInput), Object(Deployer\Console\Output\OutputWatcher))                       
  #9 /builds/***/vendor/symfony/console/Application.php(1011):
  Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console
  \Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))              
  #10                                                                            
  /builds/***/vendor/deployer/deployer/src/Console/Application
  .php(133):                                                                     
  Symfony\Component\Console\Application->doRunCommand(Object(Deployer\Console\Tas
  kCommand), Object(Symfony\Component\Console\Input\ArgvInput),                  
  Object(Deployer\Console\Output\OutputWatcher))                                 
  #11 /builds/***/vendor/symfony/console/Application.php(272):
  Deployer\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand)
  , Object(Symfony\Component\Console\Input\ArgvInput),                           
  Object(Deployer\Console\Output\OutputWatcher))                                 
  #12 /builds/***/vendor/symfony/console/Application.php(148):
  Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\I
  nput\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))       
  #13                                                                            
  /builds/***/vendor/deployer/deployer/src/Deployer.php(326): 
  Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Inp
  ut\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))         
  #14 /builds/***/vendor/deployer/deployer/bin/dep(135):      
  Deployer\Deployer::run('v6.7.2', '/builds/***.')                         
  #15 {main}                                                                     
 ERROR: Job failed: exit code 1
```

My deployer config (only showing relevant info):
```php

$phinxConfig = '{{release_path}}/phinx.php';
// Hosts
host('******')
    ->set('phinx', [
        'environment' => 'staging',
        'configuration' => $phinxConfig,
    ]);

set('phinx_path', '{{deploy_path}}/vendor/bin/phinx');

desc('Deploy your project');
task('deploy', [
    'deploy:info',
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:writable',
    'deploy:clear_paths',
    'deploy:symlink',
    'phinx:migrate',
    'deploy:unlock',
    'cleanup',
    'success',
]);

desc('Rollback failed deploy');
task('custom:rollback', [
    'phinx:rollback',
    'rollback',
    'deploy:unlock',
]);

desc('Test failure');
task('custom:testfailure', function() {
    throw new Exception("This should cause a rollback");
});

after('deploy:failed', 'custom:rollback');
before('success', 'custom:testfailure');
```

The rollback from Deployer itself and `deploy:unlock` do work (when I don't include the Phinx rollback).

Most likely, it's a configuration error, but I can't figure out where it's going wrong.

**Comment by GlennM** [comment]
No-one is using Phinx & Deployer together? :(

**Comment by poniatowski** [comment]
Hi @GlennM ! I'm wondering if you manage to fix your problem with Deployer? I'm just about to start using it and wider if it's worth and safe to use it? Do you recommend deployer for zero-downtime deployment?

**Comment by GlennM** [comment]
> Hi @GlennM ! I'm wondering if you manage to fix your problem with Deployer? I'm just about to start using it and wonder if it's worth and safe to use it? Do you recommend deployer for zero-downtime deployment?

I definitely recommend Deployer, though I did not manage to get the Phinx rollback working.
Zero-downtime deployment is possible because of the use of symlinks.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).
