### ISSUE TITLE
Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()

### ISSUE THREAD

**Issue by fritzmg** [deployphp/deployer#2002]
**Describe the bug**
`deployer/deployer` currently requires `"symfony/process": "~2.7|~3.0|~4.0|~5.0"`. However, it uses `Symfony\Component\Process\Process::fromShellCommandline()`, which does not exist in Symfony 2 or 3, only in 4 and up.

**To reproduce**

1. Install `deployer/deployer` in a project, that requires `symfony/symfony` or `symfony/process` in Version 2.8 or 3.4.
2. Use `runLocally` in your `deploy.php`.

```
[Error] Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()


 #0 vendor\deployer\deployer\src\functions.php(329):
 Deployer\Utility\ProcessRunner->run('localhost', 'gulp build', Array)
#1 deploy.php(41):
 Deployer\runLocally('gulp build')
#2 [internal function]: Deployer\Deployer::Deployer\{closure}()
#3
 vendor\deployer\deployer\src\Task\Task.php(105): call_user_func(Object(Closure))
#4
 vendor\deployer\deployer\src\Executor\SeriesExecutor.php(60):
 Deployer\Task\Task->run(Object(Deployer\Task\Context))
#5
 vendor\deployer\deployer\src\Console\TaskCommand.php(142):
 Deployer\Executor\SeriesExecutor->run(Array, Array)
#6
 vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php(255):
 Deployer\Console\TaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
 Object(Deployer\Console\Output\OutputWatcher))
#7
 vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(983):
 Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),
 Object(Deployer\Console\Output\OutputWatcher))
#8
 vendor\deployer\deployer\src\Console\Application.php(133):
 Symfony\Component\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand),
 Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))
#9
 vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(255):
 Deployer\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand),
 Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))
#10
 vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(148):
 Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
 Object(Symfony\Component\Console\Output\ConsoleOutput))
#11
 vendor\deployer\deployer\src\Deployer.php(326):
 Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),
 Object(Symfony\Component\Console\Output\ConsoleOutput))
#12
 vendor\deployer\deployer\bin\dep(135): Deployer\Deployer::run('v6.7.1',
 '...')
#13 {main}
```

**Expected behavior**
`deployer/deploy` should either change the `symfony/process` requirement accordingly or use `new Process` instead of the static factory method of Symfony 4+. The latter is probably preferred to keep Symfony 2 and 3 compatibility.

**Environment**
* Deployer version: 6.7.1
* PHP version: 7.3.12
* Deployment target(s) OS: Linux, Windows locally

**Comment by fritzmg** [comment]
Oh, never mind, this has already been fixed in `6.7.2`, but `>=6.7.2` requires at least PHP 7.2 and in this particular case the PHP version was locked to 7.1. Never mind then :)
