### ISSUE TITLE
Not possible to use add() and get() with callable on no context level

### ISSUE THREAD

**Issue by kszymukowicz** [deployphp/deployer#2033]
For now its not possible to use add() with callable. 

I need to use callable because value od `get('web_path')` is set after `set('shared_dirs', function () {`

**How to reproduce:**

```
set('shared_dirs', function () {
    return [
        get('web_path') . 'uploads',
    ];
});

add('shared_dirs', ['test']);
```

**Result:**
                                                                                                                    
```
 [RuntimeException] Configuration parameter `shared_dirs` isn't array.                                                  
                                                                                                                        
 #0 vendor/deployer/deployer/src/functions.php(531): Deployer\Deployer::addDefault('shared_dirs', Array)                                                                    
 #1 deploy.php(19): Deployer\add('shared_dirs', Array)              
 #2 vendor/deployer/deployer/src/Deployer.php(391): require('/Volumes/Data/w...')                                                                                          
 #3 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #4 vendor/deployer/deployer/src/Deployer.php(399): call_user_func(Object(Closure))                                                                                        
 #5 vendor/deployer/deployer/src/Deployer.php(325): Deployer\Deployer::loadRecipe('/Volumes/Data/w...')                                                                    
 #6 vendor/deployer/deployer/bin/dep(135): Deployer\Deployer::run('v6.7.3','/Volumes/Data/w...')                                                                 
 #7 {main}  
```

Fix:
Change 
```
    public static function addDefault($name, $array)
    {
        if (self::hasDefault($name)) {
            $config = self::getDefault($name);
            if (!is_array($config)) {
                throw new \RuntimeException("Configuration parameter `$name` isn't array.");
            }
            self::setDefault($name, array_merge_alternate($config, $array));
        } else {
            self::setDefault($name, $array);
        }
    }
```

to

```
    public static function addDefault($name, $array)
    {
        if (self::hasDefault($name)) {
            $config = self::getDefault($name);
            if(is_callable($config)) {
                $config = call_user_func($config);
            }
            if (!is_array($config)) {
                throw new \RuntimeException("Configuration parameter `$name` isn't array.");
            }
            self::setDefault($name, array_merge_alternate($config, $array));
        } else {
            self::setDefault($name, $array);
        }
    }
```

@antonmedv Plz give me a note if I can create PR for that. Tnx a lot.

**Environment**
* Deployer version: 6.7.3
* PHP version: 7.3
* Deployment target(s) OS: OSX

**Comment by kszymukowicz** [comment]
I just checked that `get()` on no context state also does not support callable.

So better is to do the change for function `getDefault()` in `src/Deployer.php`.
Right now is:
```
    public static function getDefault($name, $default = null)
    {
        return self::hasDefault($name) ? Deployer::get()->config[$name] : $default;
    }
```
and the code which fix the bug for `get()` and `add()` and also add callable for default value:

```
    public static function getDefault($name, $default = null)
    {
        if(self::hasDefault($name)) {
            $value = Deployer::get()->config[$name];
            if(is_callable($value)) {
                $value = call_user_func($value);
            }
            return $value;
        } else {
            if(is_callable($default)) {
                $default = call_user_func($default);
            }
            return $default;
        }
    }
```

**Comment by antonmedv** [comment]
Fixed in master. Please verify.

**Comment by kszymukowicz** [comment]
Master tested. 
Working as expected. 
Tnx a lot!
