### ISSUE TITLE
Order of tasks should be independent from dependencies between them

### ISSUE THREAD

**Issue by KingCrunch** [deployphp/deployer#213]
Version `3.0.0-beta.5`
```php
task('deploy', [
    'build:package'
]);

task('build:package', function () {
    // ...
})->once();
```

This currently ends up in an expception

```
deployer.phar deploy -vvv
PHP Warning:  array_map(): An error occurred while invoking the map callback in phar:///usr/local/bin/deployer.phar/src/functions.php on line 103
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/deployer.phar:0
PHP   2. require() /usr/local/bin/deployer.phar:4
PHP   3. require() phar:///usr/local/bin/deployer.phar/bin/dep:58
PHP   4. task() /home/krebs/Workspace/api-wrapper/deploy.php:17
PHP   5. array_map() phar:///usr/local/bin/deployer.phar/src/functions.php:103
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Object `build:package` does not exist in ScenarioCollection.' in phar:///usr/local/bin/deployer.phar/src/Collection/Collection.php:24
Stack trace:
#0 phar:///usr/local/bin/deployer.phar/src/Task/Scenario/ScenarioCollection.php(21): Deployer\Collection\Collection->get('build:package')
#1 phar:///usr/local/bin/deployer.phar/src/functions.php(102): Deployer\Task\Scenario\ScenarioCollection->get('build:package')
#2 [internal function]: {closure}('build:package')
#3 phar:///usr/local/bin/deployer.phar/src/functions.php(103): array_map(Object(Closure), Array)
#4 /home/krebs/Workspace/api-wrapper/deploy.php(17): task('deploy', Array)
#5 phar:///usr/local/bin/deployer.phar/bin/dep(58): require('/home/krebs/Wor...')
#6 /usr/local/bin/deployer.phar(4): require('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/deployer.phar/src/Collection/Collection.php on line 24
```

The order should be irrelevant for the definition.

**Comment by elfet** [comment]
Yes, now order of task important. Will implement irrelevant for the definition in v3.1.

**Comment by elfet** [comment]
What about task overriding? It's based on task order.

**Comment by elfet** [comment]
After little research a decided what tasks should not be independent from dependencies between them.
