### ISSUE TITLE
deployment fails on command that runs successfully when I copy/paste it into terminal

### ISSUE THREAD

**Issue by arderyp** [deployphp/deployer#2145]
I can't really provide a quick and easy way to reproduce this because its a rather complex deployment that I'm trying to sort through.  I'm more hoping for guidance on how to debug further.

My deployment fails during the stock `deploy:update_code` step with:

```
[HOST] > cd /var/www/project && (/bin/git clone -b "master" --depth 1 --recursive  git@github.MY-ENTERPRISE.com:group/project.git /var/www/project/releases/1 2>&1)
[Symfony\Component\Process\Exception\ProcessFailedException] The command "ssh -A -tt HOST 'cd /var/www/project && (/bin/git clone -b "master" --depth 1 --recursive  git@github.MY-ENTERPRISE:group/project.git /var/www/project/releases/1 2>&1)'" failed.

Exit Code: 1(General error)

Working directory: /home/project

Output:
================


Error Output:
================

#0 /home/project/vendor/deployer/deployer/src/Ssh/Client.php(76): Symfony\Component\Process\Process->mustRun()
#1 /home/project/vendor/deployer/deployer/src/functions.php(304): Deployer\Ssh\Client->run()
#2 /home/project/vendor/deployer/deployer/recipe/deploy/update_code.php(98): Deployer\run()
#3 [internal function]: Deployer\Deployer::Deployer\{closure}()
#4 /home/project/vendor/deployer/deployer/src/Task/Task.php(105): call_user_func()
#5 /home/project/vendor/deployer/deployer/src/Executor/SeriesExecutor.php(60): Deployer\Task\Task->run()
#6 /home/project/vendor/deployer/deployer/src/Console/TaskCommand.php(144): Deployer\Executor\SeriesExecutor->run()
#7 /home/project/vendor/symfony/console/Command/Command.php(255): Deployer\Console\TaskCommand->execute()
#8 /home/project/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#9 /home/project/vendor/deployer/deployer/src/Console/Application.php(133): Symfony\Component\Console\Application->doRunCommand()
#10 /home/project/vendor/symfony/console/Application.php(271): Deployer\Console\Application->doRunCommand()
#11 /home/project/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#12 /home/project/vendor/deployer/deployer/src/Deployer.php(326): Symfony\Component\Console\Application->run()
#13 /home/project/vendor/deployer/deployer/bin/dep(137): Deployer\Deployer::run()
#14 {main}
```

But, I can copy paste the failing command into the same terminal window and run it without issue:

```
$ ssh -A -tt HOST 'cd /var/www/project && (/bin/git clone -b "master" --depth 1 --recursive  git@github.MY-ENTERPRISE:group/project.git /var/www/project/releases/1 2>&1)'
Cloning into '/var/www/project/releases/1'...
remote: Enumerating objects: 1107, done.
remote: Counting objects: 100% (1107/1107), done.
remote: Compressing objects: 100% (953/953), done.
remote: Total 1107 (delta 281), reused 394 (delta 110), pack-reused 0
Receiving objects: 100% (1107/1107), 2.33 MiB | 0 bytes/s, done.
Resolving deltas: 100% (281/281), done.
Connection to HOST closed.
```

Any ideas on how I can debug this further?

**Comment by antonmedv** [comment]
Try to disable git_tty and use deploy keys.

**Comment by arderyp** [comment]
Unfortunately, that's not an option.  You can close this if you want, I've decided to stop using `become` because its just too thorny for my specific use case, and I kept running into weird problems like this and #2144
