### ISSUE TITLE
Using dev-master

### ISSUE THREAD

**Issue by ochorocho** [deployphp/deployer#2168]
**Describe the bug**
Trying to use current dev-master coz it contains a shopware6 recipe.
When trying to run `dep deploy`  it throws an error. "Task `deploy:failed` not found."

**To reproduce**

```
composer global require deployer/deployer:dev-master
dep init # in your projects directory
dep deploy
```

**Expected behavior**

I expect deployer to find the required tasks by default and not throwing an error because of missing tasks

**Environment**
* Deployer version: dev-master (685e7cbd2c04a1575800b59f75698b449f45f97e)
* PHP version: 7.3.22
* Deployment target(s) OS: MacOS Catalina 10.15.5

**Content of `deploy.php`**
```php
<?php
namespace Deployer;
define('DONT_TRACK', 'ಠ_ಠ');

require 'recipe/shopware6.php';

// Config

set('application', 'shopware-example');
set('deploy_path', '~/{{application}}');
set('repository', 'git@gitlab.knallimall.org:j.roth/shopware-example.git');

add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

// Hosts

host('shopware6-staging.knallimall.org');


// Tasks

task('build', function () {
    run('cd {{release_path}} && npm run build');
});

task('build:upload', function () {
    upload('dist', '{{release_path}}/dist');
});

// If deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

```

**Output log with enabled option for verbose output `-vvv`**
```sh
$ dep deploy -vvv
 InvalidArgumentException  in TaskCollection.php on line 20:

  Task `deploy:failed` not found.

#0 /Users/jochenr/.composer/vendor/deployer/deployer/src/Collection/Collection.php(27): Deployer\Task\TaskCollection->throwNotFound('deploy:failed')
#1 /Users/jochenr/.composer/vendor/deployer/deployer/src/functions.php(164): Deployer\Collection\Collection->get('deploy:failed')
#2 /Users/jochenr/.composer/vendor/deployer/deployer/src/functions.php(217): Deployer\task('deploy:failed')
#3 /Users/jochenr/.composer/vendor/deployer/deployer/recipe/shopware6.php(160): Deployer\after('deploy:failed', 'deploy:unlock')
#4 /Users/jochenr/Php_Projekte/shopware-example/deploy.php(5): require('/Users/jochenr/...')
#5 /Users/jochenr/.composer/vendor/deployer/deployer/src/Deployer.php(296): require('/Users/jochenr/...')
#6 [internal function]: Deployer\Deployer::Deployer\{closure}()
#7 /Users/jochenr/.composer/vendor/deployer/deployer/src/Deployer.php(305): call_user_func(Object(Closure))
#8 /Users/jochenr/.composer/vendor/deployer/deployer/src/Deployer.php(277): Deployer\Deployer::load('/Users/jochenr/...')
#9 /Users/jochenr/.composer/vendor/deployer/deployer/bin/dep(96): Deployer\Deployer::run('7.0.0-master', '/Users/jochenr/...')
#10 {main}
```

**Comment by antonmedv** [comment]
Looks like `fail()` is called somethere.
