### ISSUE TITLE
Shopware recipe doesn't break if migration throws error

### ISSUE THREAD

**Issue by Schrank** [deployphp/deployer#2757]
- Deployer version: 7-beta23
- Deployment OS: Linux

Deployer runs a recipe for shopware and migrations for the updated extensions. When the migration fails the deployment doesn't fail. **This should be changed.**

```[customer.stage.winkelwagen.de] 11:13:23 ERROR     [app] Migration: "Customer\Migration\Migration1636637799CreateShippingPrices" failed: "An exception occurred while executing 'INSERT INTO shipping_method_price (id, shipping_method_id, calculation, rule_id, calculation_rule_id, currency_price, quantity_start, quantity_end, custom_fields, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["\x22\x39\x7b\x05\x37\x73\x4c\x5d\xbf\x1e\x42\xcc\x8d\x25\xa5\x04", "\xea\x66\x4d\xc6\x49\xef\x43\x80\xa0\x0f\x0f\x28\xdb\x0f\xd9\x5a", 2, "\x88\xd3\xdd\x1c\x6f\xd9\x47\x51\x93\xcc\x1c\x26\x7c\xca\x09\x8b", null, "{\"cb7d2554b0ce847cd82f3ac9bd1c0dfca\":{\"currencyId\":\"b7d2554b0ce847cd82f3ac9bd1c0dfca\",\"gross\":6.1,\"linked\":false,\"net\":5.0}}", 0, 49.99, null, "2021-11-12 11:13:23", null]:
[customer.stage.winkelwagen.de] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '\xEAfM\xC6I\xEFC\x80\xA0\x0F\x0F(\xDB\x0F\xD9Z-\x88\xD3\xDD\x...' for key 'uniq.shipping_method_quantity_start'"
[customer.stage.winkelwagen.de]  ---------- ----------------------
[customer.stage.winkelwagen.de]   Action     Number of migrations  
[customer.stage.winkelwagen.de]  ---------- ----------------------
[customer.stage.winkelwagen.de]   Migrated   0 out of 1
[customer.stage.winkelwagen.de]  ---------- ----------------------
[customer.stage.winkelwagen.de] 11:13:23 CRITICAL  [console] Error thrown while running command "database:migrate --all Customer". Message: "Migration error: An exception occurred while executing 'INSERT INTO shipping_method_price (id, shipping_method_id, calculation, rule_id, calculation_rule_id, currency_price, quantity_start, quantity_end, custom_fields, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["\x22\x39\x7b\x05\x37\x73\x4c\x5d\xbf\x1e\x42\xcc\x8d\x25\xa5\x04", "\xea\x66\x4d\xc6\x49\xef\x43\x80\xa0\x0f\x0f\x28\xdb\x0f\xd9\x5a", 2, "\x88\xd3\xdd\x1c\x6f\xd9\x47\x51\x93\xcc\x1c\x26\x7c\xca\x09\x8b", null, "{\"cb7d2554b0ce847cd82f3ac9bd1c0dfca\":{\"currencyId\":\"b7d2554b0ce847cd82f3ac9bd1c0dfca\",\"gross\":6.1,\"linked\":false,\"net\":5.0}}", 0, 49.99, null, "2021-11-12 11:13:23", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '\xEAfM\xC6I\xEFC\x80\xA0\x0F\x0F(\xDB\x0F\xD9Z-\x88\xD3\xDD\x...' for key 'uniq.shipping_method_quantity_start'\nTrace: \n#0 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()\n#1 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(146): Doctrine\DBAL\DBALException::wrapException()\n#2 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1069): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()\n#3 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(779): Doctrine\DBAL\Connection->executeUpdate()\n#4 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/custom/static-plugins/Customer/src/Migration/Migration1636637799CreateShippingPrices.php(32): Doctrine\DBAL\Connection->insert()\n#5 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/MigrationRuntime.php(47): Customer\Migration\Migration1636637799CreateShippingPrices->update()\n#6 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(47): Shopware\Core\Framework\Migration\MigrationRuntime->migrate()\n#7 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(145): Shopware\Core\Framework\Migration\Command\MigrationCommand->getMigrationGenerator()\n#8 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(99): Shopware\Core\Framework\Migration\Command\MigrationCommand->runMigrationForIdentifier()\n#9 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Command/Command.php(255): Shopware\Core\Framework\Migration\Command\MigrationCommand->execute()\n#10 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()\n#11 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand()\n#12 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()\n#13 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()\n#14 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()\n#15 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/bin/console(68): Symfony\Component\Console\Application->run()\n#16 {main}" ["exception" => Shopware\Core\Framework\Migration\Exception\MigrateException { …},"command" => "database:migrate --all Customer","message" => """  Migration error: An exception occurred while executing 'INSERT INTO shipping_method_price (id, shipping_method_id, calculation, rule_id, calculation_rule_id, currency_price, quantity_start, quantity_end, custom_fields, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["\x22\x39\x7b\x05\x37\x73\x4c\x5d\xbf\x1e\x42\xcc\x8d\x25\xa5\x04", "\xea\x66\x4d\xc6\x49\xef\x43\x80\xa0\x0f\x0f\x28\xdb\x0f\xd9\x5a", 2, "\x88\xd3\xdd\x1c\x6f\xd9\x47\x51\x93\xcc\x1c\x26\x7c\xca\x09\x8b", null, "{\"cb7d2554b0ce847cd82f3ac9bd1c0dfca\":{\"currencyId\":\"b7d2554b0ce847cd82f3ac9bd1c0dfca\",\"gross\":6.1,\"linked\":false,\"net\":5.0}}", 0, 49.99, null, "2021-11-12 11:13:23", null]:\n  \n  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '\xEAfM\xC6I\xEFC\x80\xA0\x0F\x0F(\xDB\x0F\xD9Z-\x88\xD3\xDD\x...' for key 'uniq.shipping_method_quantity_start'\n  Trace: \n  #0 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(166): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()\n  #1 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(146): Doctrine\DBAL\DBALException::wrapException()\n  #2 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1069): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()\n  #3 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(779): Doctrine\DBAL\Connection->executeUpdate()\n  #4 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/custom/static-plugins/Customer/src/Migration/Migration1636637799CreateShippingPrices.php(32): Doctrine\DBAL\Connection->insert()\n  #5 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/MigrationRuntime.php(47): Customer\Migration\Migration1636637799CreateShippingPrices->update()\n  #6 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(47): Shopware\Core\Framework\Migration\MigrationRuntime->migrate()\n  #7 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(145): Shopware\Core\Framework\Migration\Command\MigrationCommand->getMigrationGenerator()\n  #8 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(99): Shopware\Core\Framework\Migration\Command\MigrationCommand->runMigrationForIdentifier()\n  #9 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Command/Command.php(255): Shopware\Core\Framework\Migration\Command\MigrationCommand->execute()\n  #10 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()\n  #11 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand()\n  #12 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()\n  #13 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()\n  #14 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()\n  #15 /var/www/customer.stage.winkelwagen.de/releases/20211112110946/bin/console(68): Symfony\Component\Console\Application->run()\n  #16 {main}  """]
[customer.stage.winkelwagen.de] In MigrationCommand.php line 152:
[customer.stage.winkelwagen.de]                                                                                
[customer.stage.winkelwagen.de]   Migration error: An exception occurred while executing 'INSERT INTO shippin
[customer.stage.winkelwagen.de]   g_method_price (id, shipping_method_id, calculation, rule_id, calculation_r  
[customer.stage.winkelwagen.de]   ule_id, currency_price, quantity_start, quantity_end, custom_fields, create  
[customer.stage.winkelwagen.de]   d_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["\  
[customer.stage.winkelwagen.de]   x22\x39\x7b\x05\x37\x73\x4c\x5d\xbf\x1e\x42\xcc\x8d\x25\xa5\x04", "\xea\x66  
[customer.stage.winkelwagen.de]   \x4d\xc6\x49\xef\x43\x80\xa0\x0f\x0f\x28\xdb\x0f\xd9\x5a", 2, "\x88\xd3\xdd  
[customer.stage.winkelwagen.de]   \x1c\x6f\xd9\x47\x51\x93\xcc\x1c\x26\x7c\xca\x09\x8b", null, "{\"cb7d2554b0  
[customer.stage.winkelwagen.de]   ce847cd82f3ac9bd1c0dfca\":{\"currencyId\":\"b7d2554b0ce847cd82f3ac9bd1c0dfc  
[customer.stage.winkelwagen.de]   a\",\"gross\":6.1,\"linked\":false,\"net\":5.0}}", 0, 49.99, null, "2021-11  
[customer.stage.winkelwagen.de]   -12 11:13:23", null]:                                                        
```

**Comment by antonmedv** [comment]
What the exit status of this command? Task fails in one of runs exit statue ≠ 0.

**Comment by Schrank** [comment]
run("cd {{release_or_current_path}} && bin/console database:migrate --all $plugin || true");

I'm not good with bash. This is always true, is it? So I think this is already fixed in later versions <3

**Comment by antonmedv** [comment]
Yeap. Fixed. No more ` || true`. :)
