### ISSUE TITLE
Custom deploy task, failing

### ISSUE THREAD

**Issue by nWidart** [deployphp/deployer#279]
Hello,

I'm trying to customise the deploy script, using the demo:

```
task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'deploy:cleanup'
]);
```

Now, when running `dep deploy staging -vvv` I get the following error, with stacktrace:

```
[21-May-2015 20:38:41 Europe/Berlin] PHP Fatal error:  Uncaught exception 'LogicException' with message 'An argument with name "stage" already exists.' in phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Input/InputDefinition.php:120
Stack trace:
#0 phar:///usr/local/bin/dep/src/functions.php(216): Symfony\Component\Console\Input\InputDefinition->addArgument(Object(Symfony\Component\Console\Input\InputArgument))
#1 phar:///usr/local/bin/dep/recipe/common.php(26): argument('stage', 2, 'Run tasks only ...')
#2 /Users/nicolaswidart/Sites/Asguard/presentation-site/deploy.php(4): require('phar:///usr/loc...')
#3 phar:///usr/local/bin/dep/bin/dep(58): require('/Users/nicolasw...')
#4 /usr/local/bin/dep(4): require('phar:///usr/loc...')
#5 {main}
  thrown in phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Input/InputDefinition.php on line 120
```

Here is my full `deploy.php` file:

``` php
<?php

require 'recipe/symfony.php';
require 'recipe/common.php';

server('staging', 'asgardcms.com', 22)
    ->user('forge')
    ->identityFile('~/.ssh/id_rsa.pub', '~/.ssh/id_rsa', '')
    ->stage('staging')
    ->env('deploy_path', '/home/forge/staging.asgardcms.com');

set('repository', 'git@github.com:AsgardCms/Website.git');

task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'deploy:cleanup'
]);
```

Did I miss something ?

Thanks,

**Comment by lasselehtinen** [comment]
Not sure if this is causing your problem, but you don't need to include the common recipe if you include one of the framework recipes like in your case. Try removing it and see if it helps?

Also one minor thing, the parameters to identityFile are required only if your ssh keys are not in their default place or private key has a password set. So you can do just ->identityFile().

**Comment by elfet** [comment]
Hi! You need to remove this: `require 'recipe/common.php';`

**Comment by nWidart** [comment]
Hello, thanks for you responses.

When removing the require line I get:

```
[22-May-2015 07:57:49 Europe/Berlin] PHP Warning:  array_map(): An error occurred while invoking the map callback in phar:///usr/local/bin/dep/src/functions.php on line 161
[22-May-2015 07:57:49 Europe/Berlin] PHP Stack trace:
[22-May-2015 07:57:49 Europe/Berlin] PHP   1. {main}() /usr/local/bin/dep:0
[22-May-2015 07:57:49 Europe/Berlin] PHP   2. require() /usr/local/bin/dep:4
[22-May-2015 07:57:49 Europe/Berlin] PHP   3. require() phar:///usr/local/bin/dep/bin/dep:58
[22-May-2015 07:57:49 Europe/Berlin] PHP   4. task() /Users/nicolaswidart/Sites/Asguard/presentation-site/deploy.php:19
[22-May-2015 07:57:49 Europe/Berlin] PHP   5. array_map() phar:///usr/local/bin/dep/src/functions.php:161
[22-May-2015 07:57:49 Europe/Berlin] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Object `deploy:cleanup` does not exist in ScenarioCollection.' in phar:///usr/local/bin/dep/src/Collection/Collection.php:27
Stack trace:
#0 phar:///usr/local/bin/dep/src/Task/Scenario/ScenarioCollection.php(21): Deployer\Collection\Collection->get('deploy:cleanup')
#1 phar:///usr/local/bin/dep/src/functions.php(160): Deployer\Task\Scenario\ScenarioCollection->get('deploy:cleanup')
#2 [internal function]: {closure}('deploy:cleanup')
#3 phar:///usr/local/bin/dep/src/functions.php(161): array_map(Object(Closure), Array)
#4 /Users/nicolaswidart/Sites/Asguard/presentation-site/deploy.php(19): task('deploy', Array)
#5 phar:///usr/local/bin/dep/bin/dep(58): require('/Users/nicolasw...')
#6 /usr/local/bin/dep(4): require('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/dep/src/Collection/Collection.php on line 27
```

**Comment by lasselehtinen** [comment]
That is because the symfony recipe the task name is 'cleanup', not 'deploy:cleanup'. Don't know about the Symfony recipe, but by default deploy runs the following tasks:
```
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:create_cache_dir',
    'deploy:shared',
    'deploy:writable',
    'deploy:assets',
    'deploy:vendors',
    'deploy:assetic:dump',
    'deploy:cache:warmup',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');

So you can either use that or overwrite it like you did. But anyway you need to change the deploy:cleanup to just cleanup.

**Comment by nWidart** [comment]
Ah ok thank you. Would be nice to have to docs updated then :smile:  http://deployer.org/docs/tasks .

Quick side question, how could I specify a specific branch on a git repository ?

```
set('repository', 'git@github.com:AsgardCms/Website.git');
```

Thank you ! :)

**Comment by lasselehtinen** [comment]
I agree with the docs being incomplete. I just trying out deployer but lot of the stuff is missing or is just not explained. The branch thing is one, I actually found it out by browsing through the source code.
