### ISSUE TITLE
PHP 8.4 Fatal error

### ISSUE THREAD

**Issue by garak** [deployphp/deployer#3965]
Trying to run `bin/dep deploy` I get this error:

```
Deprecated: React\Promise\Timer\timeout(): Implicitly marking parameter $loop as nullable is deprecated, the explicit nullable type must be used instead in phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/react/promise-timer/src/functions.php on line 142

Deprecated: React\Promise\Timer\sleep(): Implicitly marking parameter $loop as nullable is deprecated, the explicit nullable type must be used instead in phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/react/promise-timer/src/functions.php on line 229

Deprecated: React\Promise\Timer\resolve(): Implicitly marking parameter $loop as nullable is deprecated, the explicit nullable type must be used instead in phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/react/promise-timer/src/functions.php on line 287

Deprecated: React\Promise\Timer\reject(): Implicitly marking parameter $loop as nullable is deprecated, the explicit nullable type must be used instead in phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/react/promise-timer/src/functions.php on line 330

Fatal error: Uncaught ErrorException: Symfony\Component\Console\Input\ArgvInput::__construct(): Implicitly marking parameter $argv as nullable is deprecated, the explicit nullable type must be used instead in phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/symfony/console/Input/ArgvInput.php:46
Stack trace:
#0 phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(444): {closure:phar:///my_project/vendor/deployer/deployer/bin/dep/bin/dep:79}(8192, 'Symfony\\Compone...', 'phar:///garak/m...', 46)
#1 phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(444): include()
#2 phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///garak/m...')
#3 phar:///my_project/vendor/deployer/deployer/bin/dep/src/Deployer.php(304): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#4 phar:///my_project/vendor/deployer/deployer/bin/dep/bin/dep(96): Deployer\Deployer::run('7.5.5', '/garak/maxarion...')
#5 /my_project/vendor/deployer/deployer/bin/dep(4): require('phar:///garak/m...')
#6 /my_project/bin/dep(119): include('/garak/maxarion...')
#7 {main}
  thrown in phar:///my_project/vendor/deployer/deployer/bin/dep/vendor/symfony/console/Input/ArgvInput.php on line 46
```

**Comment by toxsick** [comment]
#3964 3963
