### ISSUE TITLE
Cannot use tasks with deployer.phar

### ISSUE THREAD

**Issue by mbrodala** [deployphp/deployer#554]
Following the guidelines to get started gives me an error:

```
$ curl -sSO http://deployer.org/releases/v3.0.10/deployer.phar
$ cat > deploy.php
<?php

task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'deploy:cleanup'
]);
$ php deployer.phar help
PHP Warning:  array_map(): An error occurred while invoking the map callback in phar:///home/me/test/deployer.phar/src/functions.php on line 168
PHP Stack trace:
PHP   1. {main}() /home/me/test/deployer.phar:0
PHP   2. require() /home/me/test/deployer.phar:4
PHP   3. require() phar:///home/me/test/deployer.phar/bin/dep:58
PHP   4. task() /home/me/test/deploy.php:9
PHP   5. array_map() phar:///home/me/test/deployer.phar/src/functions.php:168
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Object `deploy:prepare` does not exist in ScenarioCollection.' in phar:///home/me/test/deployer.phar/src/Collection/Collection.php:27
Stack trace:
#0 phar:///home/me/test/deployer.phar/src/Task/Scenario/ScenarioCollection.php(21): Deployer\Collection\Collection->get('deploy:prepare')
#1 phar:///home/me/test/deployer.phar/src/functions.php(167): Deployer\Task\Scenario\ScenarioCollection->get('deploy:prepare')
#2 [internal function]: {closure}('deploy:prepare')
#3 phar:///home/me/test/deployer.phar/src/functions.php(168): array_map(Object(Closure), Array)
#4 /home/me/test/deploy.php(9): task('deploy', Array)
#5 phar:///home/me/test/deployer.phar/bin/dep(58): require('/home/me/test...')
#6 /home/me/test/deployer.phar(4): require('phar:///home/ma...')
#7 {main}
  thrown in phar:///home/me/test/deployer.phar/src/Collection/Collection.php on line 27
```

Adding a `require 'recipe/common.php';` at the top doesn't make any difference.

How is one supposed to use recipes, tasks etc. from within the `deployer.phar`?

Installing Deployer as Composer dependency is not an option due to conflicts with other project dependencies.

**Comment by elfet** [comment]
`require 'recipe/common.php'; `?

**Comment by mbrodala** [comment]
@elfet As written in the OP this doesn't help. ;-) And I cannot imagine this to work unless Deployer adds the internal phar root path to the PHP include path at runtime.

**Comment by mbrodala** [comment]
Here again including the `require`:

```

$ curl -sSO http://deployer.org/releases/v3.0.10/deployer.phar
$ cat > deploy.php
<?php

require 'recipe/common.php';

task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'deploy:cleanup'
]);
$ php deployer.phar help
PHP Warning:  array_map(): An error occurred while invoking the map callback in phar:///tmp/test/deployer.phar/src/functions.php on line 168
PHP Stack trace:
PHP   1. {main}() /tmp/test/deployer.phar:0
PHP   2. require() /tmp/test/deployer.phar:4
PHP   3. require() phar:///tmp/test/deployer.phar/bin/dep:58
PHP   4. task($name = 'deploy', $body = array (0 => 'deploy:prepare', 1 => 'deploy:update_code', 2 => 'deploy:vendors', 3 => 'deploy:symlink', 4 => 'deploy:cleanup')) /tmp/test/deploy.php:11
PHP   5. array_map(class Closure { public $static = array ('deployer' => class Deployer\Deployer { ... }); public $parameter = array ('$name' => '<required>') }, array (0 => 'deploy:prepare', 1 => 'deploy:update_code', 2 => 'deploy:vendors', 3 => 'deploy:symlink', 4 => 'deploy:cleanup')) phar:///tmp/test/deployer.phar/src/functions.php:168

Warning: array_map(): An error occurred while invoking the map callback in phar:///tmp/test/deployer.phar/src/functions.php on line 168

Call Stack:
    0.0100     461200   1. {main}() /tmp/test/deployer.phar:0
    0.0102     465232   2. require('phar:///tmp/test/deployer.phar/bin/dep') /tmp/test/deployer.phar:4
    0.0273    2733472   3. require('/tmp/test/deploy.php') phar:///tmp/test/deployer.phar/bin/dep:58
    0.0300    2921808   4. task($name = 'deploy', $body = array (0 => 'deploy:prepare', 1 => 'deploy:update_code', 2 => 'deploy:vendors', 3 => 'deploy:symlink', 4 => 'deploy:cleanup')) /tmp/test/deploy.php:11
    0.0302    2940032   5. array_map(class Closure { public $static = array ('deployer' => class Deployer\Deployer { ... }); public $parameter = array ('$name' => '<required>') }, array (0 => 'deploy:prepare', 1 => 'deploy:update_code', 2 => 'deploy:vendors', 3 => 'deploy:symlink', 4 => 'deploy:cleanup')) phar:///tmp/test/deployer.phar/src/functions.php:168

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Object `deploy:cleanup` does not exist in ScenarioCollection.' in phar:///tmp/test/deployer.phar/src/Collection/Collection.php:27
Stack trace:
#0 phar:///tmp/test/deployer.phar/src/Task/Scenario/ScenarioCollection.php(21): Deployer\Collection\Collection->get('deploy:cleanup')
#1 phar:///tmp/test/deployer.phar/src/functions.php(167): Deployer\Task\Scenario\ScenarioCollection->get('deploy:cleanup')
#2 [internal function]: {closure}('deploy:cleanup')
#3 phar:///tmp/test/deployer.phar/src/functions.php(168): array_map(Object(Closure), Array)
#4 /tmp/test/deploy.php(11): task('deploy', Array)
#5 phar:///tmp/test/deployer.phar/bin/dep(58): require('/tmp/test/deplo...')
#6 /tmp/test/deployer.phar(4): require('phar:///tmp/tes...')
#7 {main}
  thrown in phar:///tmp/test/deployer.phar/src/Collection/Collection.php on line 27

Fatal error: Uncaught exception 'RuntimeException' with message 'Object `deploy:cleanup` does not exist in ScenarioCollection.' in phar:///tmp/test/deployer.phar/src/Collection/Collection.php on line 27

RuntimeException: Object `deploy:cleanup` does not exist in ScenarioCollection. in phar:///tmp/test/deployer.phar/src/Collection/Collection.php on line 27

Call Stack:
    0.0100     461200   1. {main}() /tmp/test/deployer.phar:0
    0.0102     465232   2. require('phar:///tmp/test/deployer.phar/bin/dep') /tmp/test/deployer.phar:4
    0.0273    2733472   3. require('/tmp/test/deploy.php') phar:///tmp/test/deployer.phar/bin/dep:58
    0.0300    2921808   4. task($name = 'deploy', $body = array (0 => 'deploy:prepare', 1 => 'deploy:update_code', 2 => 'deploy:vendors', 3 => 'deploy:symlink', 4 => 'deploy:cleanup')) /tmp/test/deploy.php:11
    0.0302    2940032   5. array_map(class Closure { public $static = array ('deployer' => class Deployer\Deployer { ... }); public $parameter = array ('$name' => '<required>') }, array (0 => 'deploy:prepare', 1 => 'deploy:update_code', 2 => 'deploy:vendors', 3 => 'deploy:symlink', 4 => 'deploy:cleanup')) phar:///tmp/test/deployer.phar/src/functions.php:168
    0.0303    2941504   6. {closure:phar:///tmp/test/deployer.phar/src/functions.php:166-168}($name = 'deploy:cleanup') phar:///tmp/test/deployer.phar/src/functions.php:168
    0.0303    2941504   7. Deployer\Task\Scenario\ScenarioCollection->get($name = 'deploy:cleanup') phar:///tmp/test/deployer.phar/src/functions.php:167
    0.0303    2941504   8. Deployer\Collection\Collection->get($name = 'deploy:cleanup') phar:///tmp/test/deployer.phar/src/Task/Scenario/ScenarioCollection.php:21
```

**Comment by tliegl** [comment]
Put this at the end of your deploy.php

`task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'deploy:cleanup'
]);`

Had the same problem and the order of the tasks is somehow important.

**Comment by mbrodala** [comment]
@tliegl Not sure I understand but this is what I already have in my `deploy.php`.

**Comment by tliegl** [comment]
I had this with my own tasks. I wrote the group task at the top of my deploy.php and added the single tasks below it - I got the same error as you. After that I moved the single tasks at the top of the deploy.php and moved the group task at the end of the file. Then the error was gone.

**Comment by mbrodala** [comment]
@tliegl Can you post your exact `deploy.php`?

The example I posted is taken straight from the docs and ATM I don't want/need to define custom tasks; I simply want to use a selection of tasks from the recipes. Thus in the most basic case all I want is a task group like this.

**Comment by alaczi** [comment]
Hm, in common recipe the cleanup task has no deploy prefix:

**Comment by oanhnn** [comment]
:+1: Thank @alaczi 
@mbrodala , please try:
```
<?php

require 'recipe/common.php';

task('deploy', [
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'cleanup'
]);
```

**Comment by mbrodala** [comment]
@alaczi You where absolutely right about this, this fixes the issue. I've made a [PR which fixes this error in the docs](https://github.com/deployphp/docs/pull/50).
