### ISSUE TITLE
Windows: doesn't work also with ext-ssh2

### ISSUE THREAD

**Issue by fede91it** [deployphp/deployer#830]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 3.3.0
| Local Machine OS  | Windows 10 x64 LTSB 2016
| Remote Machine OS | N/A

### Description 
I've installed ext-ssh2 in my PHP environment but deployer still doesn't work, this is the error when I try to deploy my Laravel app (generated recipe).

### Steps to reproduce

Run `dep deploy -vvv`, nothing else.

### Content of `deploy.php`
```php
<?php
/*
 * This file has been generated automatically.
 * Please change the configuration for correct use deploy.
 */

require 'recipe/laravel.php';

// Set configurations
set('repository', 'git@bitbucket.org:fede91it/thejuicesqueezer-laravel.git');
set('shared_files', ['.env']);
set('shared_dirs', [
    'storage/app',
    'storage/framework/cache',
    'storage/framework/sessions',
    'storage/framework/views',
    'storage/logs',
]);
set('writable_dirs', ['bootstrap/cache', 'storage']);
set('ssh_type', 'ext-ssh2');

server('production', '77.104.141.250', 18765)
	->env('deploy_path', '/public_html/_beta')
	->user('thejuice')
    ->forwardAgent();
```

### Output log

```
λ dep deploy beta --verbose
Ô×ñ Executing task deploy:prepare
Ôå│ on [beta]
PHP Fatal error:  Uncaught Error: Class 'Ssh\Configuration' not found in C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Server\Remote\SshExtension.php:47
Stack trace:
#0 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\recipe\common.php(105): Deployer\Server\Remote\SshExtension->connect()
#1 [internal function]: {closure}()
#2 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Task\Task.php(79): call_user_func(Object(Closure))
#3 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Executor\SeriesExecutor.php(43): Deployer\Task\Task->run(Object(Deployer\Task\Context))
#4 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Console\TaskCommand.php(82): Deployer\Executor\SeriesExecutor->run(Array, Array, Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))
#5 C:\Users\Federico\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php(256): Deployer\Console\TaskComman in C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Server\Remote\SshExtension.php on line 47

Fatal error: Uncaught Error: Class 'Ssh\Configuration' not found in C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Server\Remote\SshExtension.php:47
Stack trace:
#0 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\recipe\common.php(105): Deployer\Server\Remote\SshExtension->connect()
#1 [internal function]: {closure}()
#2 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Task\Task.php(79): call_user_func(Object(Closure))
#3 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Executor\SeriesExecutor.php(43): Deployer\Task\Task->run(Object(Deployer\Task\Context))
#4 C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Console\TaskCommand.php(82): Deployer\Executor\SeriesExecutor->run(Array, Array, Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))
#5 C:\Users\Federico\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php(256): Deployer\Console\TaskComman in C:\Users\Federico\AppData\Roaming\Composer\vendor\deployer\deployer\src\Server\Remote\SshExtension.php on line 47
```

**Comment by fede91it** [comment]
Anyone could help here?

**Comment by elfet** [comment]
Did you installed *herzult/php-ssh*?

**Comment by fede91it** [comment]
Thank you, it worked!

I open a new issue for another thing.
