### ISSUE TITLE
Error while deploying "Class Deployer/Type/Csv not found" 

### ISSUE THREAD

**Issue by rmasclef** [deployphp/deployer#892]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.0.1
| Local Machine OS  | Debian 8.6
| Remote Machine OS | Debian 8.6

### Description 
When launching a dep deploy, the script crashes on `deploy:release` task.

### Steps to reproduce
The first call is OK. Starting the second one, the error appears.

### Content of `deploy.php`
```php
<?php
namespace Deployer;

//use the symfony 3 recipe
require __DIR__.'/../vendor/deployer/deployer/recipe/symfony3.php';

/**
 * =====================================================================================================================
 * ============================================== CONFIGURATION ========================================================
 * =====================================================================================================================
*/

// Define servers connections
serverList(__DIR__.'/servers.yml');

//Use ssh2 to communicate with the servers
set('ssh_type', 'ext-ssh2');
//Use ACL as writable mode
set('writable_mode', 'acl');
set('writable_use_sudo', true);
//By default, the deployment will be done on dev server
//Prevent the user from deploying on prod env if he did not specified a stage
set('default_stage', 'development');
//Give the craft project git repo
set('repository', 'git@gitlab.com:experian/craft.git');

/**
 * =====================================================================================================================
 * ================================================= TASK ==============================================================
 * =====================================================================================================================
 */

//@FIXME Works but its awful !
desc('Change permission on log file and session file for the first release');
task('deploy:permissions', function () {
    if (get('release_name') === '1') {
        run('chmod 777 {{release_path}}/var/logs/'.get('env').'.log');
    }
});

//Define the apache restart task
desc('Restart apache service');
task('apache:restart', function () {
    // The user must have rights for restart service
    run('sudo /etc/init.d/apache2 restart');
});

after('deploy:symlink', 'deploy:permissions');
//restart the apache service on the server after deploy:permission task
after('deploy:permissions', 'apache:restart');
```

### Content of `servers.yml`
```yml
dev:
  host: 192.168.80.145
  user: craft
  identity_file: ~
  stage: development
  deploy_path: /home/craft/public_html
  branch: develop
  env: dev
  composer_options: '{{composer_action}} --verbose --prefer-dist --no-interaction --optimize-autoloader'
  clear_paths:
    - web/config.php
```

### Output log
```
➤ Executing task deploy:prepare
[dev] > echo $0
[dev] < bash
[dev] > if [ ! -d /home/craft/public_html ]; then mkdir -p /home/craft/public_html; fi
[dev] > if [ ! -L /home/craft/public_html/current ] && [ -d /home/craft/public_html/current ]; then echo true; fi
[dev] > cd /home/craft/public_html && if [ ! -d .dep ]; then mkdir .dep; fi
[dev] > cd /home/craft/public_html && if [ ! -d releases ]; then mkdir releases; fi
[dev] > cd /home/craft/public_html && if [ ! -d shared ]; then mkdir shared; fi
• done on [dev]
✔ Ok [713ms]
➤ Executing task deploy:lock
[dev] > if [ -f /home/craft/public_html/.dep/deploy.lock ]; then echo 'true'; fi
[dev] > touch /home/craft/public_html/.dep/deploy.lock
• done on [dev]
✔ Ok [98ms]
➤ Executing task deploy:release
[dev] > cd /home/craft/public_html && (if [ -h release ]; then echo 'true'; fi)
[dev] > cd /home/craft/public_html && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[dev] < true
[dev] > cd /home/craft/public_html && (cd releases && ls -t -d */)
[dev] < 1/
[dev] > cd /home/craft/public_html && (if [ -f .dep/releases ]; then echo "true"; fi)
[dev] < true
[dev] > cd /home/craft/public_html && (tail -n 10 .dep/releases)
[dev] < 20161122093615,1
[dev] < 20161122094142,1
PHP Fatal error:  Uncaught Error: Class 'Deployer\Type\Csv' not found in /home/deployer/projects/vendor/deployer/deployer/recipe/deploy/release.php:60
Stack trace:
#0 [internal function]: Deployer\{closure}()
#1 phar:///usr/local/bin/dep/src/Server/Environment.php(126): call_user_func(Object(Closure))
#2 phar:///usr/local/bin/dep/src/functions.php(498): Deployer\Server\Environment->get('releases_list', NULL)
#3 /home/deployer/projects/vendor/deployer/deployer/recipe/deploy/release.php(13): Deployer\get('releases_list')
#4 [internal function]: Deployer\{closure}()
#5 phar:///usr/local/bin/dep/src/Server/Environment.php(126): call_user_func(Object(Closure))
#6 phar:///usr/local/bin/dep/src/functions.php(498): Deployer\Server\Environment->get('release_name', NULL)
#7 /home/deployer/projects/vendor/deployer/deployer/recipe/deploy/release.php(106): Deployer\get('release_name')
#8 [internal function]: Deployer\{closure}()
#9 phar:///usr/local/bin/dep/src/Task/Task.php(91): call_user_func(Object(Closure))
#10 phar:///usr/local/bin/de in /home/deployer/projects/vendor/deployer/deployer/recipe/deploy/release.php on line 60
```

**Comment by elfet** [comment]
Check `usr/local/bin/dep` version.

**Comment by rmasclef** [comment]
good point I didn't make a dep self-update on the server.

I let you now if this solves the problem (probably yes).

**Comment by rmasclef** [comment]
Works when updating `usr/local/bin` dep :)

**Comment by elfet** [comment]
Btw, new deployer must detect if vendor contains dep, and run composer version instead of. May be possible bug with not detecting it...
